In [2]:
import pandas as pd  # keywords are highlighted in green, other strings in red, etc.
import numpy as np

In [3]:
file= pd.read_excel('marketing_customer_analysis.xlsx')
display(file.head()) #first 5 lines. note index of row is the same as a number of a row
display(file.tail())
file.shape

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0.0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,0.0,9.0,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1.0,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,0.0,1.0,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2.0,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,0.0,2.0,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3.0,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,0.0,2.0,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4.0,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,NaN,7.0,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
10905,10905.0,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,...,NaN,7.0,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A
10906,10906.0,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,...,0.0,6.0,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A
10907,10907.0,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,...,0.0,2.0,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,NaN
10908,10908.0,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,...,4.0,6.0,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A
10909,10909.0,IV32877,NaN,6857.519928,NaN,Basic,Bachelor,2011-01-08,Unemployed,M,...,0.0,3.0,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,NaN

(10910, 26)

In [4]:
cols = []
for colname in file.columns:
    cols.append(colname.lower())
file.columns = cols
display(file.head())

,unnamed: 0,customer,state,customer lifetime value,response,coverage,education,effective to date,employmentstatus,gender,...,number of open complaints,number of policies,policy type,policy,renew offer type,sales channel,total claim amount,vehicle class,vehicle size,vehicle type
0,0.0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,0.0,9.0,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1.0,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,0.0,1.0,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2.0,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,0.0,2.0,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3.0,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,0.0,2.0,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4.0,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,NaN,7.0,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [8]:
data1=file._get_numeric_data() #numerical
data2=file.select_dtypes(include=['object']).columns #whih columns are categorical
print(data1)
print(data2)

       unnamed: 0  customer lifetime value   income  monthly premium auto  \
0             0.0              4809.216960  48029.0                  61.0
1             1.0              2228.525238      0.0                  64.0
2             2.0             14947.917300  22139.0                 100.0
3             3.0             22332.439460  49078.0                  97.0
4             4.0              9025.067525  23675.0                 117.0
...           ...                      ...      ...                   ...
10905     10905.0             15563.369440      0.0                 253.0
10906     10906.0              5259.444853  61146.0                  65.0
10907     10907.0             23893.304100  39837.0                 201.0
10908     10908.0             11971.977650  64195.0                 158.0
10909     10909.0              6857.519928      0.0                 101.0

       months since last claim  months since policy inception  \
0                          7.0                           52.0
1                          3.0                           26.0
2                         34.0                           31.0
3                         10.0                            3.0
4                          NaN                           31.0
...                        ...                            ...
10905                      NaN                           40.0
10906                      7.0                           68.0
10907                     11.0                           63.0
10908                      0.0                           27.0
10909                     31.0                            1.0

       number of open complaints  number of policies  total claim amount
0                            0.0                 9.0          292.800000
1                            0.0                 1.0          744.924331
2                            0.0                 2.0          480.000000
3                            0.0                 2.0          484.013411
4                            NaN                 7.0          707.925645
...                          ...                 ...                 ...
10905                        NaN                 7.0         1214.400000
10906                        0.0                 6.0          273.018929
10907                        0.0                 2.0          381.306996
10908                        4.0                 6.0          618.288849
10909                        0.0                 3.0         1021.719397

[10910 rows x 9 columns]
Index(['customer', 'state', 'response', 'coverage', 'education',
       'employmentstatus', 'gender', 'location code', 'marital status',
       'policy type', 'policy', 'renew offer type', 'sales channel',
       'vehicle class', 'vehicle size', 'vehicle type'],
      dtype='object')

In [45]:
#how many missing values has each column
file.isna().sum()

unnamed: 0                          0
customer                            0
state                             631
customer lifetime value             0
response                          631
coverage                            0
education                           0
effective to date                   0
employmentstatus                    0
gender                              0
income                              0
location code                       0
marital status                      0
monthly premium auto                0
months since last claim           633
months since policy inception       0
number of open complaints         633
number of policies                  0
policy type                         0
policy                              0
renew offer type                    0
sales channel                       0
total claim amount                  0
vehicle class                     622
vehicle size                      622
vehicle type                     5482
month                               0
dtype: int64

In [50]:
len(file) #10910
(5482/10910)*100 #50% vehicle
(622/10910)*100 #5.7% vehicle size and vehicle class
(633/10910)*100 #5.8% months since last claim and number of open complaints
(631/10910)*100 #5.7% state and response

5.783684692942255

In [51]:
nulls_data = pd.DataFrame(round(file.isna().sum()/len(file),4)*100) # shows the percentage of null values in a column
nulls_data = nulls_data.reset_index()
display(nulls_data)

# a lot of missing data in vehicle type

                            index      0
0                      unnamed: 0   0.00
1                        customer   0.00
2                           state   5.78
3         customer lifetime value   0.00
4                        response   5.78
5                        coverage   0.00
6                       education   0.00
7               effective to date   0.00
8                employmentstatus   0.00
9                          gender   0.00
10                         income   0.00
11                  location code   0.00
12                 marital status   0.00
13           monthly premium auto   0.00
14        months since last claim   5.80
15  months since policy inception   0.00
16      number of open complaints   5.80
17             number of policies   0.00
18                    policy type   0.00
19                         policy   0.00
20               renew offer type   0.00
21                  sales channel   0.00
22             total claim amount   0.00
23                  vehicle class   5.70
24                   vehicle size   5.70
25                   vehicle type  50.25
26                          month   0.00

In [60]:
#as there is a lot of missing data in vehicle type and we have better data in vehicle class and vehicle size
# I decided to remove the whole column verhicle type. After I reset index.
filedrop = file.drop('vehicle type', axis=1)
filedrop.shape
display(filedrop.head())
filedrop=filedrop.reset_index()

,unnamed: 0,customer,state,customer lifetime value,response,coverage,education,effective to date,employmentstatus,gender,...,number of open complaints,number of policies,policy type,policy,renew offer type,sales channel,total claim amount,vehicle class,vehicle size,month
0,0.0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,0.0,9.0,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,2
1,1.0,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,0.0,1.0,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,1
2,2.0,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,0.0,2.0,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,2
3,3.0,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,0.0,2.0,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,1
4,4.0,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,NaN,7.0,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,1

In [62]:
filedrop[filedrop['vehicle class'].isna()==True].head(60) #we see first 60 rows with NaN in vehicle class
#By observing this table, we can see that vehicle class and vehicle size miss the information together.

,index,unnamed: 0,customer,state,customer lifetime value,response,coverage,education,effective to date,employmentstatus,...,number of open complaints,number of policies,policy type,policy,renew offer type,sales channel,total claim amount,vehicle class,vehicle size,month
87,87,87.0,ZH92587,Oregon,8126.766397,No,Basic,College,2011-02-22,Disabled,...,NaN,3.0,Personal Auto,Personal L3,Offer1,Agent,513.600000,NaN,NaN,2
88,88,88.0,CJ51511,Arizona,13466.920710,Yes,Basic,High School or Below,2011-02-23,Disabled,...,NaN,2.0,Corporate Auto,Corporate L3,Offer2,Agent,571.200000,NaN,NaN,2
89,89,89.0,ME37450,Arizona,5210.348372,No,Basic,Bachelor,2011-01-04,Employed,...,0.0,5.0,Special Auto,Special L2,Offer1,Agent,37.960537,NaN,NaN,1
97,97,97.0,CA22248,Oregon,2505.420430,No,Basic,Master,2011-02-14,Employed,...,0.0,1.0,Personal Auto,Personal L3,Offer2,Branch,46.278027,NaN,NaN,2
148,148,148.0,HB24005,California,2347.048112,No,Basic,College,2011-02-02,Employed,...,1.0,1.0,Personal Auto,Personal L1,Offer1,Agent,244.269407,NaN,NaN,2
163,163,163.0,TP34946,California,5108.038755,No,Basic,College,2011-01-09,Disabled,...,0.0,8.0,Corporate Auto,Corporate L3,Offer3,Branch,482.400000,NaN,NaN,1
186,186,186.0,BG42047,Nevada,2511.944048,No,Basic,College,2011-01-15,Medical Leave,...,0.0,1.0,Personal Auto,Personal L3,Offer3,Web,312.000000,NaN,NaN,1
205,205,205.0,YZ19736,Arizona,2580.849899,Yes,Basic,College,2011-02-09,Employed,...,0.0,1.0,Personal Auto,Personal L2,Offer2,Web,316.800000,NaN,NaN,2
224,224,224.0,KL65897,California,6331.338496,No,Extended,Bachelor,2011-02-21,Unemployed,...,0.0,3.0,Personal Auto,Personal L2,Offer1,Branch,94.714302,NaN,NaN,2
261,261,261.0,HZ56678,Oregon,2780.196856,No,Basic,High School or Below,2011-01-12,Disabled,...,0.0,1.0,Personal Auto,Personal L2,Offer4,Web,345.600000,NaN,NaN,1
294,294,294.0,AM57175,Oregon,15000.842380,No,Extended,High School or Below,2011-01-06,Employed,...,1.0,2.0,Personal Auto,Personal L3,Offer1,Branch,507.560729,NaN,NaN,1
301,301,301.0,JP35025,California,5714.165863,No,Basic,Master,2011-02-23,Disabled,...,0.0,9.0,Corporate Auto,Corporate L1,Offer1,Call Center,355.200000,NaN,NaN,2
346,346,346.0,YC69616,Arizona,2719.506996,Yes,Basic,College,2011-01-24,Retired,...,0.0,1.0,Personal Auto,Personal L3,Offer2,Branch,345.600000,NaN,NaN,1
367,367,367.0,VY90611,California,2499.036551,No,Basic,Master,2011-01-27,Employed,...,NaN,1.0,Corporate Auto,Corporate L3,Offer2,Agent,364.622773,NaN,NaN,1
397,397,397.0,XV69290,California,22332.439460,Yes,Extended,College,2011-01-11,Employed,...,0.0,2.0,Corporate Auto,Corporate L2,Offer2,Branch,484.013411,NaN,NaN,1
416,416,416.0,EO40136,Arizona,2912.248444,No,Basic,College,2011-01-24,Employed,...,0.0,1.0,Personal Auto,Personal L2,Offer2,Web,295.224598,NaN,NaN,1
426,426,426.0,GE82737,Nevada,5337.352409,No,Extended,Bachelor,2011-02-14,Unemployed,...,3.0,5.0,Personal Auto,Personal L3,Offer1,Agent,619.200000,NaN,NaN,2
448,448,448.0,GT66241,California,2414.072446,No,Basic,High School or Below,2011-01-08,Unemployed,...,0.0,1.0,Personal Auto,Personal L3,Offer2,Call Center,511.200000,NaN,NaN,1
457,457,457.0,BZ85280,Oregon,7284.262288,No,Basic,College,2011-02-23,Medical Leave,...,0.0,2.0,Personal Auto,Personal L1,Offer3,Agent,296.962938,NaN,NaN,2
480,480,480.0,EC71986,Washington,2429.280527,No,Basic,High School or Below,2011-01-18,Medical Leave,...,0.0,1.0,Personal Auto,Personal L1,Offer1,Agent,367.927730,NaN,NaN,1
489,489,489.0,GU42671,Arizona,6106.941981,No,Extended,Bachelor,2011-02-21,Medical Leave,...,0.0,7.0,Personal Auto,Personal L3,Offer1,Branch,379.200000,NaN,NaN,2
491,491,491.0,IE97795,NaN,6878.008403,NaN,Extended,High School or Below,2011-02-05,Employed,...,0.0,5.0,Corporate Auto,Corporate L1,Offer3,Agent,485.013840,NaN,NaN,2
494,494,494.0,AY55759,California,20096.893370,Yes,Basic,High School or Below,2011-01-01,Employed,...,0.0,2.0,Personal Auto,Personal L2,Offer2,Agent,379.029102,NaN,NaN,1
547,547,547.0,FL85008,Oregon,13466.920710,Yes,Basic,High School or Below,2011-02-23,Disabled,...,0.0,2.0,Personal Auto,Personal L2,Offer2,Agent,571.200000,NaN,NaN,2
554,554,554.0,AU23837,Oregon,5010.379310,No,Basic,Bachelor,2011-01-19,Employed,...,0.0,7.0,Corporate Auto,Corporate L3,Offer1,Agent,295.871784,NaN,NaN,1
577,577,577.0,GQ46925,Arizona,5821.684337,No,Premium,High School or Below,2011-02-15,Employed,...,0.0,1.0,Personal Auto,Personal L1,Offer4,Call Center,545.999699,NaN,NaN,2
586,586,586.0,GZ79662,Arizona,5484.588155,No,Basic,High School or Below,2011-02-21,Employed,...,0.0,4.0,Corporate Auto,Corporate L3,Offer2,Call Center,593.654484,NaN,NaN,2
601,601,601.0,OA92714,California,5055.902381,No,Basic,Bachelor,2011-01-10,Employed,...,1.0,3.0,Personal Auto,Personal L3,Offer3,Call Center,232.745161,NaN,NaN,1
634,634,634.0,DH34004,California,6191.402312,No,Basic,College,2011-02-06,Unemployed,...,3.0,1.0,Personal Auto,Personal L3,Offer2,Web,955.200000,NaN,NaN,2
636,636,636.0,HM94328,Arizona,6047.025160,Yes,Extended,College,2011-02-19,Employed,...,1.0,4.0,Corporate Auto,Corporate L2,Offer1,Branch,364.800000,NaN,NaN,2
644,644,644.0,SK12432,Arizona,2388.353882,No,Basic,Bachelor,2011-02-14,Unemployed,...,0.0,1.0,Personal Auto,Personal L1,Offer2,Web,677.970934,NaN,NaN,2
650,650,650.0,JP58047,Oregon,8332.730557,No,Extended,College,2011-01-27,Unemployed,...,0.0,2.0,Personal Auto,Personal L3,Offer2,Web,379.200000,NaN,NaN,1
668,668,668.0,KH58171,California,2551.226692,Yes,Basic,Master,2011-01-19,Employed,...,0.0,1.0,Personal Auto,Personal L3,Offer3,Web,392.235698,NaN,NaN,1
672,672,672.0,GJ47397,Oregon,38055.209530,No,Basic,High School or Below,2011-02-12,Unemployed,...,0.0,2.0,Special Auto,Special L2,Offer2,Agent,552.000000,NaN,NaN,2
679,679,679.0,EZ41764,California,2498.963061,No,Basic,Bachelor,2011-02-26,Employed,...,0.0,1.0,Personal Auto,Personal L2,Offer3,Agent,297.600000,NaN,NaN,2
683,683,683.0,KC36987,Oregon,13334.267630,No,Premium,Bachelor,2011-01-20,Employed,...,1.0,8.0,Personal Auto,Personal L3,Offer1,Branch,780.990942,NaN,NaN,1
691,691,691.0,ID89933,Oregon,7255.577594,No,Extended,Doctor,2011-01-09,Employed,...,NaN,9.0,Personal Auto,Personal L2,Offer1,Web,365.835977,NaN,NaN,1
716,716,716.0,ZZ49347,Oregon,2592.437797,Yes,Basic,High School or Below,2011-01-02,Employed,...,0.0,1.0,Personal Auto,Personal L3,Offer2,Call Center,312.000000,NaN,NaN,1
718,718,718.0,KW95891,Oregon,2635.148447,No,Basic,High School or Below,2011-01-28,Employed,...,0.0,1.0,Personal Auto,Personal L3,Offer4,Branch,312.000000,NaN,NaN,1
744,744,744.0,KH24214,NaN,17857.972330,NaN,Basic,College,2011-02-13,Employed,...,1.0,2.0,Personal Auto,Personal L3,Offer3,Agent,445.287788,NaN,NaN,2
756,756,756.0,VX85673,Arizona,4250.282624,Yes,Basic,High School or Below,2011-01-18,Unemployed,...,1.0,7.0,Personal Auto,Personal L3,Offer1,Agent,292.800000,NaN,NaN,1
761,761,761.0,XH47320,Nevada,2937.424534,No,Basic,Master,2011-01-10,Employed,...,1.0,1.0,Personal Auto,Personal L1,Offer1,Call Center,332.693627,NaN,NaN,1
786,786,786.0,HF11584,Arizona,12913.498180,No,Basic,Master,2011-01-11,Employed,...,0.0,2.0,Personal Auto,Personal L3,Offer1,Branch,513.600000,NaN,NaN,1
856,856,856.0,CF62992,Oregon,2471.077732,No,Basic,High School or Below,2011-01-16,Employed,...,0.0,1.0,Personal Auto,Personal L2,Offer1,Agent,268.773368,NaN,NaN,1
888,888,888.0,ED28429,Washington,4159.593921,No,Basic,Bachelor,2011-02-01,Unemployed,...,0.0,3.0,Personal Auto,Personal L1,Offer1,Agent,446.400000,NaN,NaN,2
929,929,929.0,BB11622,Nevada,10552.169990,No,Extended,Master,2011-01-02,Employed,...,0.0,6.0,Personal Auto,Personal L3,Offer1,Agent,232.711071,NaN,NaN,1
933,933,933.0,YT91759,California,6366.225775,Yes,Extended,High School or Below,2011-01-07,Employed,...,0.0,3.0,Personal Auto,Personal L2,Offer2,Call Center,384.000000,NaN,NaN,1
950,950,950.0,ID89933,Oregon,7255.577594,No,Extended,Doctor,2011-01-09,Employed,...,1.0,9.0,Personal Auto,Personal L2,Offer1,Web,365.835977,NaN,NaN,1
972,972,972.0,MG46007,California,6358.251692,No,Extended,High School or Below,2011-01-24,Unemployed,...,2.0,4.0,Personal Auto,Personal L2,Offer1,Agent,17.938979,NaN,NaN,1
979,979,979.0,BA52133,California,5344.989624,No,Basic,Master,2011-02-11,Employed,...,0.0,7.0,Personal Auto,Personal L2,Offer3,Call Center,387.774781,NaN,NaN,2
982,982,982.0,TK61994,Oregon,6104.501453,No,Extended,College,2011-02-28,Disabled,...,0.0,5.0,Personal Auto,Personal L2,Offer1,Agent,18.192921,NaN,NaN,2
993,993,993.0,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2011-02-28,Employed,...,0.0,1.0,Personal Auto,Personal L3,Offer2,Agent,60.036683,NaN,NaN,2
1024,1024,1024.0,VE72838,Arizona,13770.976180,Yes,Premium,High School or Below,2011-02-01,Employed,...,0.0,2.0,Personal Auto,Personal L3,Offer1,Agent,556.800000,NaN,NaN,2
1046,1046,1046.0,LD75023,Oregon,26346.085820,No,Extended,High School or Below,2011-01-20,Employed,...,0.0,2.0,Personal Auto,Personal L2,Offer1,Web,1605.600000,NaN,NaN,1
1065,1065,1065.0,BU72633,Nevada,42561.631830,No,Basic,Master,2011-01-10,Employed,...,0.0,2.0,Personal Auto,Personal L2,Offer1,Agent,571.200000,NaN,NaN,1
1075,1075,1075.0,ES57969,Oregon,2453.570794,Yes,Basic,Bachelor,2011-02-09,Medical Leave,...,0.0,1.0,Personal Auto,Personal L2,Offer1,Agent,331.200000,NaN,NaN,2
1078,1078,1078.0,YI73667,Nevada,5340.810309,No,Basic,College,2011-01-17,Unemployed,...,0.0,6.0,Personal Auto,Personal L3,Offer2,Web,345.600000,NaN,NaN,1
1109,1109,1109.0,CE72177,California,5461.548993,No,Basic,High School or Below,2011-01-07,Employed,...,0.0,3.0,Personal Auto,Personal L3,Offer2,Agent,485.705851,NaN,NaN,1
1127,1127,1127.0,ZW19492,Oregon,2404.917967,No,Basic,Bachelor,2011-02-14,Employed,...,0.0,1.0,Personal Auto,Personal L3,Offer1,Branch,287.654819,NaN,NaN,2
1130,1130,1130.0,XW96958,Nevada,7573.345057,No,Premium,High School or Below,2011-02-20,Unemployed,...,0.0,6.0,Corporate Auto,Corporate L3,Offer1,Agent,1193.036154,NaN,NaN,2

In [66]:
filedrop[filedrop['number of open complaints'].isna()==True].head(60)
filedrop['number of open complaints'].unique() # array([ 0., nan,  3.,  1.,  2.,  4.,  5.])
filedrop['number of open complaints'].nunique() #6
#I am afraid to replace nan with other possible variables. So I think we should keep it

array([ 0., nan,  3.,  1.,  2.,  4.,  5.])

In [71]:
filedrop[filedrop['state'].isna()==True].head(60)
#filedrop['state'].unique() # array(['Arizona', 'California', 'Washington', 'Oregon', nan, 'Nevada'],
      
#filedrop['number of open complaints'].nunique() #6
#I am afraid to replace nan with other possible variables. So I think we should keep it
#state nan is connected with response nan.

,index,unnamed: 0,customer,state,customer lifetime value,response,coverage,education,effective to date,employmentstatus,...,number of open complaints,number of policies,policy type,policy,renew offer type,sales channel,total claim amount,vehicle class,vehicle size,month
5,5,5.0,HO81102,NaN,4745.181764,NaN,Basic,High School or Below,2011-02-14,Employed,...,0.0,7.0,Personal Auto,Personal L3,Offer1,Agent,292.800000,Four-Door Car,Medsize,2
11,11,11.0,GE63585,NaN,2420.711888,NaN,Basic,Bachelor,2011-02-07,Employed,...,0.0,1.0,Corporate Auto,Corporate L3,Offer1,Call Center,199.551735,Two-Door Car,Medsize,2
58,58,58.0,BR69566,NaN,14019.833140,NaN,Basic,College,2011-02-18,Employed,...,0.0,2.0,Personal Auto,Personal L3,Offer4,Call Center,469.882367,Two-Door Car,Small,2
62,62,62.0,UF44021,NaN,2108.493744,NaN,Basic,Bachelor,2011-01-02,Unemployed,...,0.0,1.0,Personal Auto,Personal L2,Offer1,Agent,351.856810,Two-Door Car,Medsize,1
126,126,126.0,TE60343,NaN,4716.264294,NaN,Basic,High School or Below,2011-02-25,Employed,...,1.0,3.0,Corporate Auto,Corporate L3,Offer2,Agent,292.800000,Four-Door Car,Medsize,2
131,131,131.0,QK24293,NaN,6265.343299,NaN,Extended,Doctor,2011-01-13,Unemployed,...,1.0,4.0,Corporate Auto,Corporate L1,Offer1,Agent,481.025786,Four-Door Car,Medsize,1
155,155,155.0,JG35886,NaN,4111.888285,NaN,Premium,College,2011-01-21,Employed,...,0.0,1.0,Personal Auto,Personal L2,Offer2,Call Center,480.073548,Four-Door Car,Medsize,1
168,168,168.0,FV22585,NaN,6960.920371,NaN,Extended,College,2011-02-04,Employed,...,0.0,3.0,Personal Auto,Personal L1,Offer1,Call Center,16.711329,Four-Door Car,Medsize,2
169,169,169.0,AU23837,NaN,5010.379310,NaN,Basic,Bachelor,2011-01-19,Employed,...,NaN,7.0,Corporate Auto,Corporate L3,Offer1,Agent,295.871784,Four-Door Car,Large,1
190,190,190.0,VZ18907,NaN,21991.615980,NaN,Basic,College,2011-01-12,Employed,...,0.0,2.0,Personal Auto,Personal L3,Offer2,Branch,132.139111,SUV,Large,1
226,226,226.0,VK57280,NaN,4727.354548,NaN,Basic,Bachelor,2011-01-03,Unemployed,...,0.0,3.0,Personal Auto,Personal L2,Offer2,Call Center,345.600000,Four-Door Car,Medsize,1
251,251,251.0,EA52579,NaN,7687.296987,NaN,Basic,Bachelor,2011-02-26,Unemployed,...,0.0,3.0,Personal Auto,Personal L1,Offer3,Call Center,523.200000,SUV,Medsize,2
270,270,270.0,KX23516,NaN,4455.843406,NaN,Extended,High School or Below,2011-02-20,Unemployed,...,0.0,1.0,Personal Auto,Personal L3,Offer4,Agent,699.615192,SUV,Medsize,2
304,304,304.0,PP39078,NaN,5623.611187,NaN,Basic,College,2011-02-19,Employed,...,0.0,3.0,Special Auto,Special L1,Offer4,Branch,340.800000,Four-Door Car,Small,2
305,305,305.0,WZ83320,NaN,9061.057741,NaN,Premium,Master,2011-02-18,Employed,...,0.0,8.0,Personal Auto,Personal L1,Offer3,Web,419.303041,Four-Door Car,Medsize,2
321,321,321.0,WQ85760,NaN,4260.335730,NaN,Basic,College,2011-02-05,Medical Leave,...,0.0,1.0,Corporate Auto,Corporate L3,Offer3,Branch,856.800000,SUV,Medsize,2
323,323,323.0,GF70857,NaN,2933.960426,NaN,Extended,College,2011-01-28,Unemployed,...,0.0,1.0,Personal Auto,Personal L3,Offer2,Call Center,199.851201,Four-Door Car,Medsize,1
329,329,329.0,OE15600,NaN,2544.969754,NaN,Basic,College,2011-02-06,Employed,...,NaN,1.0,Personal Auto,Personal L3,Offer2,Call Center,139.745936,Two-Door Car,Medsize,2
334,334,334.0,AV76907,NaN,4282.947971,NaN,Basic,College,2011-02-26,Employed,...,1.0,1.0,Personal Auto,Personal L3,Offer1,Agent,166.937747,SUV,Medsize,2
347,347,347.0,WT71621,NaN,3280.457296,NaN,Extended,Bachelor,2011-02-02,Employed,...,0.0,1.0,Personal Auto,Personal L3,Offer2,Web,251.756739,Four-Door Car,Medsize,2
385,385,385.0,OQ61223,NaN,17497.522010,NaN,Basic,College,2011-02-28,Unemployed,...,0.0,2.0,Personal Auto,Personal L2,Offer1,Agent,350.400000,Two-Door Car,Medsize,2
403,403,403.0,ET47892,NaN,12280.766610,NaN,Premium,College,2011-01-01,Employed,...,0.0,2.0,Personal Auto,Personal L3,Offer1,Branch,489.600000,Two-Door Car,Medsize,1
404,404,404.0,XD19546,NaN,8160.689782,NaN,Basic,High School or Below,2011-01-21,Unemployed,...,0.0,7.0,Personal Auto,Personal L1,Offer1,Web,523.200000,SUV,Medsize,1
430,430,430.0,AB96670,NaN,2393.915369,NaN,Basic,College,2011-01-31,Unemployed,...,0.0,1.0,Personal Auto,Personal L1,Offer1,Branch,425.266308,Four-Door Car,Medsize,1
455,455,455.0,PO56357,NaN,5363.528173,NaN,Basic,High School or Below,2011-01-01,Employed,...,1.0,8.0,Personal Auto,Personal L3,Offer1,Web,272.445607,Four-Door Car,Medsize,1
475,475,475.0,MB20764,NaN,17622.133200,NaN,Premium,High School or Below,2011-02-18,Unemployed,...,0.0,3.0,Corporate Auto,Corporate L2,Offer4,Branch,1814.400000,Luxury SUV,Medsize,2
478,478,478.0,DO98345,NaN,13156.748950,NaN,Extended,High School or Below,2011-02-28,Employed,...,0.0,2.0,Personal Auto,Personal L3,Offer2,Web,371.458196,Two-Door Car,Medsize,2
491,491,491.0,IE97795,NaN,6878.008403,NaN,Extended,High School or Below,2011-02-05,Employed,...,0.0,5.0,Corporate Auto,Corporate L1,Offer3,Agent,485.013840,NaN,NaN,2
574,574,574.0,WR85740,NaN,8149.769437,NaN,Basic,Doctor,2011-01-26,Unemployed,...,0.0,2.0,Corporate Auto,Corporate L3,Offer2,Call Center,340.800000,Two-Door Car,Medsize,1
595,595,595.0,TN17395,NaN,22103.507200,NaN,Basic,College,2011-01-30,Unemployed,...,0.0,2.0,Personal Auto,Personal L3,Offer1,Branch,489.600000,SUV,Medsize,1
597,597,597.0,EP64069,NaN,5138.244998,NaN,Basic,Bachelor,2011-01-08,Employed,...,0.0,9.0,Corporate Auto,Corporate L3,Offer3,Web,272.649844,Four-Door Car,Medsize,1
605,605,605.0,OD18225,NaN,6631.665538,NaN,Extended,College,2011-01-18,Employed,...,0.0,3.0,Personal Auto,Personal L2,Offer3,Agent,403.200000,Four-Door Car,Medsize,1
648,648,648.0,RS29507,NaN,10395.709390,NaN,Extended,Bachelor,2011-02-10,Unemployed,...,0.0,2.0,Personal Auto,Personal L3,Offer2,Agent,337.797690,Four-Door Car,Medsize,2
662,662,662.0,YS94121,NaN,5645.396665,NaN,Basic,High School or Below,2011-02-27,Employed,...,0.0,9.0,Personal Auto,Personal L1,Offer1,Call Center,428.734656,Four-Door Car,Small,2
670,670,670.0,RL51023,NaN,4185.757242,NaN,Basic,College,2011-02-16,Unemployed,...,0.0,3.0,Corporate Auto,Corporate L1,Offer2,Call Center,492.644465,Four-Door Car,Small,2
686,686,686.0,NQ71171,NaN,5107.071054,NaN,Basic,Bachelor,2011-02-02,Employed,...,0.0,7.0,Personal Auto,Personal L2,Offer1,Agent,128.900320,Four-Door Car,Medsize,2
690,690,690.0,OO11998,NaN,4583.748377,NaN,Basic,Master,2011-01-19,Employed,...,4.0,1.0,Personal Auto,Personal L2,Offer1,Branch,764.592151,SUV,Medsize,1
720,720,720.0,ON74557,NaN,14651.615300,NaN,Extended,Bachelor,2011-01-06,Employed,...,0.0,2.0,Personal Auto,Personal L2,Offer3,Branch,393.151377,SUV,Medsize,1
725,725,725.0,JC33752,NaN,6277.844624,NaN,Extended,College,2011-01-21,Employed,...,1.0,9.0,Personal Auto,Personal L3,Offer2,Agent,450.129276,Two-Door Car,Large,1
726,726,726.0,SY86059,NaN,3731.504584,NaN,Extended,High School or Below,2011-02-24,Unemployed,...,NaN,1.0,Corporate Auto,Corporate L3,Offer1,Agent,460.800000,Four-Door Car,Large,2
729,729,729.0,BV86143,NaN,21034.018150,NaN,Basic,High School or Below,2011-02-23,Employed,...,0.0,2.0,Personal Auto,Personal L2,Offer4,Call Center,219.209762,Four-Door Car,Medsize,2
732,732,732.0,QR45101,NaN,6624.611830,NaN,Basic,Bachelor,2011-02-26,Unemployed,...,0.0,2.0,Corporate Auto,Corporate L3,Offer1,Branch,297.600000,Two-Door Car,Medsize,2
740,740,740.0,RB63074,NaN,4858.067125,NaN,Basic,High School or Below,2011-01-03,Unemployed,...,0.0,3.0,Personal Auto,Personal L1,Offer2,Branch,482.400000,Four-Door Car,Medsize,1
744,744,744.0,KH24214,NaN,17857.972330,NaN,Basic,College,2011-02-13,Employed,...,1.0,2.0,Personal Auto,Personal L3,Offer3,Agent,445.287788,NaN,NaN,2
745,745,745.0,PB39857,NaN,5129.608404,NaN,Extended,Master,2011-02-23,Employed,...,0.0,1.0,Personal Auto,Personal L3,Offer2,Agent,343.139611,SUV,Large,2
764,764,764.0,ZY57929,NaN,8169.746083,NaN,Basic,College,2011-01-26,Employed,...,0.0,3.0,Personal Auto,Personal L2,Offer1,Agent,499.200000,SUV,Medsize,1
781,781,781.0,GI55977,NaN,2337.351820,NaN,Basic,High School or Below,2011-02-23,Medical Leave,...,0.0,1.0,Personal Auto,Personal L1,Offer2,Call Center,292.800000,Four-Door Car,Small,2
785,785,785.0,KN13494,NaN,5181.620895,NaN,Basic,Master,2011-02-03,Employed,...,NaN,6.0,Personal Auto,Personal L1,Offer2,Agent,307.200000,Four-Door Car,Small,2
794,794,794.0,RZ97514,NaN,7498.824515,NaN,Basic,Master,2011-01-27,Unemployed,...,0.0,2.0,Personal Auto,Personal L1,Offer3,Agent,316.800000,Four-Door Car,Medsize,1
796,796,796.0,KE61355,NaN,5272.703428,NaN,Basic,High School or Below,2011-02-16,Employed,...,0.0,3.0,Corporate Auto,Corporate L1,Offer2,Web,328.366827,Four-Door Car,Medsize,2
814,814,814.0,UU70820,NaN,5867.126420,NaN,Basic,College,2011-02-22,Employed,...,0.0,5.0,Personal Auto,Personal L3,Offer2,Call Center,199.444294,Four-Door Car,Large,2
857,857,857.0,HD44279,NaN,5090.448750,NaN,Basic,Bachelor,2011-02-08,Disabled,...,1.0,4.0,Personal Auto,Personal L2,Offer1,Branch,340.800000,Four-Door Car,Medsize,2
859,859,859.0,PD30266,NaN,5015.643575,NaN,Extended,College,2011-02-10,Employed,...,0.0,1.0,Special Auto,Special L1,Offer1,Branch,537.315879,SUV,Medsize,2
878,878,878.0,QN62502,NaN,3839.143697,NaN,Extended,Bachelor,2011-02-07,Employed,...,0.0,1.0,Personal Auto,Personal L1,Offer2,Branch,157.440069,Four-Door Car,Medsize,2
890,890,890.0,EN38348,NaN,23207.269720,NaN,Extended,High School or Below,2011-01-16,Employed,...,0.0,2.0,Personal Auto,Personal L2,Offer1,Agent,192.144838,Four-Door Car,Large,1
895,895,895.0,ON44465,NaN,5313.294035,NaN,Extended,High School or Below,2011-01-24,Unemployed,...,1.0,9.0,Personal Auto,Personal L2,Offer1,Agent,863.394700,Four-Door Car,Medsize,1
900,900,900.0,XP92021,NaN,13295.602840,NaN,Basic,High School or Below,2011-02-27,Employed,...,0.0,2.0,Personal Auto,Personal L1,Offer1,Call Center,528.000000,SUV,Medsize,2
906,906,906.0,DP63956,NaN,6791.215414,NaN,Basic,Bachelor,2011-01-10,Unemployed,...,1.0,8.0,Corporate Auto,Corporate L2,Offer1,Agent,727.200000,SUV,Large,1
908,908,908.0,GG84614,NaN,3031.587812,NaN,Extended,High School or Below,2011-01-08,Employed,...,0.0,1.0,Personal Auto,Personal L3,Offer3,Branch,455.545318,Two-Door Car,Medsize,1
909,909,909.0,MD15300,NaN,10110.769970,NaN,Extended,College,2011-02-05,Employed,...,0.0,2.0,Corporate Auto,Corporate L3,Offer4,Web,93.309811,Two-Door Car,Large,2

In [74]:
filedrop[filedrop['response'].isna()==True].head(60)
#filedrop['response'].unique() # array(['No', 'Yes', nan]

,index,unnamed: 0,customer,state,customer lifetime value,response,coverage,education,effective to date,employmentstatus,...,number of open complaints,number of policies,policy type,policy,renew offer type,sales channel,total claim amount,vehicle class,vehicle size,month
5,5,5.0,HO81102,NaN,4745.181764,NaN,Basic,High School or Below,2011-02-14,Employed,...,0.0,7.0,Personal Auto,Personal L3,Offer1,Agent,292.800000,Four-Door Car,Medsize,2
11,11,11.0,GE63585,NaN,2420.711888,NaN,Basic,Bachelor,2011-02-07,Employed,...,0.0,1.0,Corporate Auto,Corporate L3,Offer1,Call Center,199.551735,Two-Door Car,Medsize,2
58,58,58.0,BR69566,NaN,14019.833140,NaN,Basic,College,2011-02-18,Employed,...,0.0,2.0,Personal Auto,Personal L3,Offer4,Call Center,469.882367,Two-Door Car,Small,2
62,62,62.0,UF44021,NaN,2108.493744,NaN,Basic,Bachelor,2011-01-02,Unemployed,...,0.0,1.0,Personal Auto,Personal L2,Offer1,Agent,351.856810,Two-Door Car,Medsize,1
126,126,126.0,TE60343,NaN,4716.264294,NaN,Basic,High School or Below,2011-02-25,Employed,...,1.0,3.0,Corporate Auto,Corporate L3,Offer2,Agent,292.800000,Four-Door Car,Medsize,2
131,131,131.0,QK24293,NaN,6265.343299,NaN,Extended,Doctor,2011-01-13,Unemployed,...,1.0,4.0,Corporate Auto,Corporate L1,Offer1,Agent,481.025786,Four-Door Car,Medsize,1
155,155,155.0,JG35886,NaN,4111.888285,NaN,Premium,College,2011-01-21,Employed,...,0.0,1.0,Personal Auto,Personal L2,Offer2,Call Center,480.073548,Four-Door Car,Medsize,1
168,168,168.0,FV22585,NaN,6960.920371,NaN,Extended,College,2011-02-04,Employed,...,0.0,3.0,Personal Auto,Personal L1,Offer1,Call Center,16.711329,Four-Door Car,Medsize,2
169,169,169.0,AU23837,NaN,5010.379310,NaN,Basic,Bachelor,2011-01-19,Employed,...,NaN,7.0,Corporate Auto,Corporate L3,Offer1,Agent,295.871784,Four-Door Car,Large,1
190,190,190.0,VZ18907,NaN,21991.615980,NaN,Basic,College,2011-01-12,Employed,...,0.0,2.0,Personal Auto,Personal L3,Offer2,Branch,132.139111,SUV,Large,1
226,226,226.0,VK57280,NaN,4727.354548,NaN,Basic,Bachelor,2011-01-03,Unemployed,...,0.0,3.0,Personal Auto,Personal L2,Offer2,Call Center,345.600000,Four-Door Car,Medsize,1
251,251,251.0,EA52579,NaN,7687.296987,NaN,Basic,Bachelor,2011-02-26,Unemployed,...,0.0,3.0,Personal Auto,Personal L1,Offer3,Call Center,523.200000,SUV,Medsize,2
270,270,270.0,KX23516,NaN,4455.843406,NaN,Extended,High School or Below,2011-02-20,Unemployed,...,0.0,1.0,Personal Auto,Personal L3,Offer4,Agent,699.615192,SUV,Medsize,2
304,304,304.0,PP39078,NaN,5623.611187,NaN,Basic,College,2011-02-19,Employed,...,0.0,3.0,Special Auto,Special L1,Offer4,Branch,340.800000,Four-Door Car,Small,2
305,305,305.0,WZ83320,NaN,9061.057741,NaN,Premium,Master,2011-02-18,Employed,...,0.0,8.0,Personal Auto,Personal L1,Offer3,Web,419.303041,Four-Door Car,Medsize,2
321,321,321.0,WQ85760,NaN,4260.335730,NaN,Basic,College,2011-02-05,Medical Leave,...,0.0,1.0,Corporate Auto,Corporate L3,Offer3,Branch,856.800000,SUV,Medsize,2
323,323,323.0,GF70857,NaN,2933.960426,NaN,Extended,College,2011-01-28,Unemployed,...,0.0,1.0,Personal Auto,Personal L3,Offer2,Call Center,199.851201,Four-Door Car,Medsize,1
329,329,329.0,OE15600,NaN,2544.969754,NaN,Basic,College,2011-02-06,Employed,...,NaN,1.0,Personal Auto,Personal L3,Offer2,Call Center,139.745936,Two-Door Car,Medsize,2
334,334,334.0,AV76907,NaN,4282.947971,NaN,Basic,College,2011-02-26,Employed,...,1.0,1.0,Personal Auto,Personal L3,Offer1,Agent,166.937747,SUV,Medsize,2
347,347,347.0,WT71621,NaN,3280.457296,NaN,Extended,Bachelor,2011-02-02,Employed,...,0.0,1.0,Personal Auto,Personal L3,Offer2,Web,251.756739,Four-Door Car,Medsize,2
385,385,385.0,OQ61223,NaN,17497.522010,NaN,Basic,College,2011-02-28,Unemployed,...,0.0,2.0,Personal Auto,Personal L2,Offer1,Agent,350.400000,Two-Door Car,Medsize,2
403,403,403.0,ET47892,NaN,12280.766610,NaN,Premium,College,2011-01-01,Employed,...,0.0,2.0,Personal Auto,Personal L3,Offer1,Branch,489.600000,Two-Door Car,Medsize,1
404,404,404.0,XD19546,NaN,8160.689782,NaN,Basic,High School or Below,2011-01-21,Unemployed,...,0.0,7.0,Personal Auto,Personal L1,Offer1,Web,523.200000,SUV,Medsize,1
430,430,430.0,AB96670,NaN,2393.915369,NaN,Basic,College,2011-01-31,Unemployed,...,0.0,1.0,Personal Auto,Personal L1,Offer1,Branch,425.266308,Four-Door Car,Medsize,1
455,455,455.0,PO56357,NaN,5363.528173,NaN,Basic,High School or Below,2011-01-01,Employed,...,1.0,8.0,Personal Auto,Personal L3,Offer1,Web,272.445607,Four-Door Car,Medsize,1
475,475,475.0,MB20764,NaN,17622.133200,NaN,Premium,High School or Below,2011-02-18,Unemployed,...,0.0,3.0,Corporate Auto,Corporate L2,Offer4,Branch,1814.400000,Luxury SUV,Medsize,2
478,478,478.0,DO98345,NaN,13156.748950,NaN,Extended,High School or Below,2011-02-28,Employed,...,0.0,2.0,Personal Auto,Personal L3,Offer2,Web,371.458196,Two-Door Car,Medsize,2
491,491,491.0,IE97795,NaN,6878.008403,NaN,Extended,High School or Below,2011-02-05,Employed,...,0.0,5.0,Corporate Auto,Corporate L1,Offer3,Agent,485.013840,NaN,NaN,2
574,574,574.0,WR85740,NaN,8149.769437,NaN,Basic,Doctor,2011-01-26,Unemployed,...,0.0,2.0,Corporate Auto,Corporate L3,Offer2,Call Center,340.800000,Two-Door Car,Medsize,1
595,595,595.0,TN17395,NaN,22103.507200,NaN,Basic,College,2011-01-30,Unemployed,...,0.0,2.0,Personal Auto,Personal L3,Offer1,Branch,489.600000,SUV,Medsize,1
597,597,597.0,EP64069,NaN,5138.244998,NaN,Basic,Bachelor,2011-01-08,Employed,...,0.0,9.0,Corporate Auto,Corporate L3,Offer3,Web,272.649844,Four-Door Car,Medsize,1
605,605,605.0,OD18225,NaN,6631.665538,NaN,Extended,College,2011-01-18,Employed,...,0.0,3.0,Personal Auto,Personal L2,Offer3,Agent,403.200000,Four-Door Car,Medsize,1
648,648,648.0,RS29507,NaN,10395.709390,NaN,Extended,Bachelor,2011-02-10,Unemployed,...,0.0,2.0,Personal Auto,Personal L3,Offer2,Agent,337.797690,Four-Door Car,Medsize,2
662,662,662.0,YS94121,NaN,5645.396665,NaN,Basic,High School or Below,2011-02-27,Employed,...,0.0,9.0,Personal Auto,Personal L1,Offer1,Call Center,428.734656,Four-Door Car,Small,2
670,670,670.0,RL51023,NaN,4185.757242,NaN,Basic,College,2011-02-16,Unemployed,...,0.0,3.0,Corporate Auto,Corporate L1,Offer2,Call Center,492.644465,Four-Door Car,Small,2
686,686,686.0,NQ71171,NaN,5107.071054,NaN,Basic,Bachelor,2011-02-02,Employed,...,0.0,7.0,Personal Auto,Personal L2,Offer1,Agent,128.900320,Four-Door Car,Medsize,2
690,690,690.0,OO11998,NaN,4583.748377,NaN,Basic,Master,2011-01-19,Employed,...,4.0,1.0,Personal Auto,Personal L2,Offer1,Branch,764.592151,SUV,Medsize,1
720,720,720.0,ON74557,NaN,14651.615300,NaN,Extended,Bachelor,2011-01-06,Employed,...,0.0,2.0,Personal Auto,Personal L2,Offer3,Branch,393.151377,SUV,Medsize,1
725,725,725.0,JC33752,NaN,6277.844624,NaN,Extended,College,2011-01-21,Employed,...,1.0,9.0,Personal Auto,Personal L3,Offer2,Agent,450.129276,Two-Door Car,Large,1
726,726,726.0,SY86059,NaN,3731.504584,NaN,Extended,High School or Below,2011-02-24,Unemployed,...,NaN,1.0,Corporate Auto,Corporate L3,Offer1,Agent,460.800000,Four-Door Car,Large,2
729,729,729.0,BV86143,NaN,21034.018150,NaN,Basic,High School or Below,2011-02-23,Employed,...,0.0,2.0,Personal Auto,Personal L2,Offer4,Call Center,219.209762,Four-Door Car,Medsize,2
732,732,732.0,QR45101,NaN,6624.611830,NaN,Basic,Bachelor,2011-02-26,Unemployed,...,0.0,2.0,Corporate Auto,Corporate L3,Offer1,Branch,297.600000,Two-Door Car,Medsize,2
740,740,740.0,RB63074,NaN,4858.067125,NaN,Basic,High School or Below,2011-01-03,Unemployed,...,0.0,3.0,Personal Auto,Personal L1,Offer2,Branch,482.400000,Four-Door Car,Medsize,1
744,744,744.0,KH24214,NaN,17857.972330,NaN,Basic,College,2011-02-13,Employed,...,1.0,2.0,Personal Auto,Personal L3,Offer3,Agent,445.287788,NaN,NaN,2
745,745,745.0,PB39857,NaN,5129.608404,NaN,Extended,Master,2011-02-23,Employed,...,0.0,1.0,Personal Auto,Personal L3,Offer2,Agent,343.139611,SUV,Large,2
764,764,764.0,ZY57929,NaN,8169.746083,NaN,Basic,College,2011-01-26,Employed,...,0.0,3.0,Personal Auto,Personal L2,Offer1,Agent,499.200000,SUV,Medsize,1
781,781,781.0,GI55977,NaN,2337.351820,NaN,Basic,High School or Below,2011-02-23,Medical Leave,...,0.0,1.0,Personal Auto,Personal L1,Offer2,Call Center,292.800000,Four-Door Car,Small,2
785,785,785.0,KN13494,NaN,5181.620895,NaN,Basic,Master,2011-02-03,Employed,...,NaN,6.0,Personal Auto,Personal L1,Offer2,Agent,307.200000,Four-Door Car,Small,2
794,794,794.0,RZ97514,NaN,7498.824515,NaN,Basic,Master,2011-01-27,Unemployed,...,0.0,2.0,Personal Auto,Personal L1,Offer3,Agent,316.800000,Four-Door Car,Medsize,1
796,796,796.0,KE61355,NaN,5272.703428,NaN,Basic,High School or Below,2011-02-16,Employed,...,0.0,3.0,Corporate Auto,Corporate L1,Offer2,Web,328.366827,Four-Door Car,Medsize,2
814,814,814.0,UU70820,NaN,5867.126420,NaN,Basic,College,2011-02-22,Employed,...,0.0,5.0,Personal Auto,Personal L3,Offer2,Call Center,199.444294,Four-Door Car,Large,2
857,857,857.0,HD44279,NaN,5090.448750,NaN,Basic,Bachelor,2011-02-08,Disabled,...,1.0,4.0,Personal Auto,Personal L2,Offer1,Branch,340.800000,Four-Door Car,Medsize,2
859,859,859.0,PD30266,NaN,5015.643575,NaN,Extended,College,2011-02-10,Employed,...,0.0,1.0,Special Auto,Special L1,Offer1,Branch,537.315879,SUV,Medsize,2
878,878,878.0,QN62502,NaN,3839.143697,NaN,Extended,Bachelor,2011-02-07,Employed,...,0.0,1.0,Personal Auto,Personal L1,Offer2,Branch,157.440069,Four-Door Car,Medsize,2
890,890,890.0,EN38348,NaN,23207.269720,NaN,Extended,High School or Below,2011-01-16,Employed,...,0.0,2.0,Personal Auto,Personal L2,Offer1,Agent,192.144838,Four-Door Car,Large,1
895,895,895.0,ON44465,NaN,5313.294035,NaN,Extended,High School or Below,2011-01-24,Unemployed,...,1.0,9.0,Personal Auto,Personal L2,Offer1,Agent,863.394700,Four-Door Car,Medsize,1
900,900,900.0,XP92021,NaN,13295.602840,NaN,Basic,High School or Below,2011-02-27,Employed,...,0.0,2.0,Personal Auto,Personal L1,Offer1,Call Center,528.000000,SUV,Medsize,2
906,906,906.0,DP63956,NaN,6791.215414,NaN,Basic,Bachelor,2011-01-10,Unemployed,...,1.0,8.0,Corporate Auto,Corporate L2,Offer1,Agent,727.200000,SUV,Large,1
908,908,908.0,GG84614,NaN,3031.587812,NaN,Extended,High School or Below,2011-01-08,Employed,...,0.0,1.0,Personal Auto,Personal L3,Offer3,Branch,455.545318,Two-Door Car,Medsize,1
909,909,909.0,MD15300,NaN,10110.769970,NaN,Extended,College,2011-02-05,Employed,...,0.0,2.0,Corporate Auto,Corporate L3,Offer4,Web,93.309811,Two-Door Car,Large,2

In [59]:

#Datetime format - Extract the months from the dataset and store in a separate column. 
#extractedData = file[[7]]
#data = pd.DataFrame({'Effective To Date'})

file['month'] = pd.DatetimeIndex(file['effective to date']).month #it's at the back of the table
file.head()
y = file[['month']]
print (y)
file[(file['month']==1) | (file['month']==2) | (file['month']==3) ]

firstkw= file[(file['month']==1) | (file['month']==2) | (file['month']==3)]
display(firstkw.head())

       month
0          2
1          1
2          2
3          1
4          1
...      ...
10905      1
10906      1
10907      2
10908      2
10909      1

[10910 rows x 1 columns]

,unnamed: 0,customer,state,customer lifetime value,response,coverage,education,effective to date,employmentstatus,gender,...,number of policies,policy type,policy,renew offer type,sales channel,total claim amount,vehicle class,vehicle size,vehicle type,month
0,0.0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9.0,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN,2
1,1.0,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1.0,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN,1
2,2.0,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2.0,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3.0,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2.0,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4.0,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7.0,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN,1